<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Vuleticd
 * @package     Vuleticd_OrderHistory
 * @copyright   Copyright (c) 2015 Vuletic Dragan (http://www.vuleticd.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $block \Vuleticd\OrderHistory\Block\Order\Old */ ?>
<?php $order = $block->getOrder(); ?>
<ul class="items order-links">
	<li class="nav item current"><strong>Items Ordered</strong>
	</li>
</ul>

<div class="order-details-items ordered">
    <div class="order-title">
        <strong>Items Ordered</strong>
    </div>
    <div class="table-wrapper order-items">
		<table summary="Items Ordered" id="my-orders-table" class="data table table-order-items">
			<caption class="table-caption">Items Ordered</caption>
			<thead>
				<tr>
					<th class="col name">Product Name</th>
					<th class="col sku">SKU</th>
					<th class="col price">Price</th>
					<th class="col qty">Qty</th>
					<th class="col subtotal">Subtotal</th>
				</tr>
			</thead>
			<tbody>
					<tr id="order-item-row-3">
						<td data-th="Product Name" class="col name">
						</td>
					</tr>
			</tbody>
			<tfoot>
				<tr class="subtotal">
					<th scope="row" class="mark" colspan="4">Subtotal</th>
					<td data-th="Subtotal" class="amount">
						<span class="price"><?php echo $order->getSubtotal(); ?></span>                    
					</td>
				</tr>
				<tr class="shipping">
					<th scope="row" class="mark" colspan="4">Shipping &amp; Handling</th>
						<td data-th="Shipping &amp; Handling" class="amount">
							<span class="price"><?php echo $order->getShippingAmount(); ?></span>                    
						</td>
					</tr>
					<tr class="grand_total">
						<th scope="row" class="mark" colspan="4">
							<strong>Estimated Total</strong>
						</th>
						<td data-th="Estimated Total" class="amount">
							<strong><span class="price"><?php echo $order->getGrandTotal(); ?></span></strong>
						</td>
					</tr>
			</tfoot>
		</table>
	</div>  
    <div class="actions-toolbar">
        <div class="secondary">
            <a href="/sales/order/history/" class="action back">
                <span>Back to My Orders</span>
            </a>
        </div>
    </div>
</div>

<div class="block block-order-details-view">
    <div class="block-title">
        <strong>Order Information</strong>
    </div>
    <div class="block-content">
		<div class="box box-order-shipping-address">
			<strong class="box-title"><span>Shipping Address</span></strong>
			<div class="box-content">
				<address><?php echo $order->getShippingAddress(); ?></address>
			</div>
		</div>

		<div class="box box-order-shipping-method">
			<strong class="box-title">
				<span>Shipping Method</span>
			</strong>
			<div class="box-content"><?php echo $order->getShippingMethod(); ?></div>
		</div>

		<div class="box box-order-billing-address">
			<strong class="box-title">
				<span>Billing Address</span>
			</strong>
			<div class="box-content">
				<address><?php echo $order->getBillingAddress(); ?></address>
			</div>
		</div>
		<div class="box box-order-billing-method">
			<strong class="box-title">
				<span>Payment Method</span>
			</strong>
			<div class="box-content">
				<dl class="payment-method checkmemo">
					<dt class="title"><?php echo $order->getPaymentMethod(); ?></dt>
				</dl>
			</div>
		</div>
	</div>
</div>


